// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Bio       sql.NullString
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
