// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          int64
	Slug        string
	Title       string
	Description string
	Body        string
	AuthorID    int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ArticleTag struct {
	ArticleID int64
	TagID     int64
}

type Comment struct {
	ID        int64
	Body      string
	ArticleID int64
	AuthorID  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Favorite struct {
	UserID    int64
	ArticleID int64
	CreatedAt time.Time
}

type Follow struct {
	FollowerID int64
	FollowedID int64
	CreatedAt  time.Time
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	Bio       sql.NullString
	Image     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
